version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    environment:
      
      REACT_APP_API_URL: "http://localhost:4040/"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4040:4040"   
    environment:
      DATABASE_URL: "file:./dev.db"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    depends_on:
      - minio
    env_file:
      - ./server/.env

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:9000"   
      - "9001:9001"   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
